### ISSUE TITLE
Could not update statistic com.plugtree.solrmeter.model.exception.StatisticConnectionException: java.lang.ClassCastException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tflobbe/solrmeter#118]
```
What steps will reproduce the problem?

Run solrmeter and monitor cache statistics

What is the expected output? What do you see instead?

[Thread-1207]|ERROR|[CacheHistoryStatistic]|13:20:02,374 | Could not update 
statistic
com.plugtree.solrmeter.model.exception.StatisticConnectionException: 
java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.String
	at com.plugtree.solrmeter.model.statistic.RequestHandlerConnection.getData(RequestHandlerConnection.java:72)
	at com.plugtree.solrmeter.model.statistic.CacheHistoryStatistic.updateData(CacheHistoryStatistic.java:114)
	at com.plugtree.solrmeter.model.statistic.CacheHistoryStatistic$StatisticUpdateThread.run(CacheHistoryStatistic.java:163)
Caused by: java.lang.ClassCastException: java.lang.Float cannot be cast to 
java.lang.String
	at com.plugtree.solrmeter.model.statistic.RequestHandlerConnection.getCacheData(RequestHandlerConnection.java:84)
	at com.plugtree.solrmeter.model.statistic.RequestHandlerConnection.getData(RequestHandlerConnection.java:62)
	... 2 more


What version of the product are you using? On what operating system?

solrmeter-0.3.0.jar, SOLR 4.6.0

Please provide any additional information below.

In SOLR 4.4 hit ratio was changed from String to float in the JMX interface. 
See also:
https://issues.apache.org/jira/browse/SOLR-4616
https://github.com/apache/lucene-solr/commit/17e8ee6573e69567ff7221e7907db38c600
33bf2

```

Original issue reported on code.google.com by `thomas.p...@gmail.com` on 13 Jan 2014 at 12:49

**Comment by tflobbe** [comment]
Resolved with the patch and fixed the test case
